const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const model = {};
vm.createContext(model);
vm.runInContext(fs.readFileSync(path.join(__dirname, '../ChartModel.js'), 'utf8'), model);
assert.equal(model.shift('2026-03-30', -1), '2026-03-29');
assert.equal(model.shift('2026-01-01', -1), '2025-12-31');
const week = model.week([{date:'2026-08-19', tokens:1000}, {date:'2026-08-25', tokens:0}], '2026-08-25');
assert.equal(week.rows.length, 7);
assert.equal(week.rows[0].date, '2026-08-19');
assert.equal(week.rows[1].tokens, null);
assert.equal(week.rows[6].tokens, 0);
assert.equal(week.total, 1000);
assert.equal(week.count, 2);
assert.equal(week.peak, 1000);
assert.equal(model.week([], '2026-09-15').count, 0);
assert.equal(model.compact(null), '–');
assert.equal(model.compact(0), '0');
assert.equal(model.compact(1e9), '1B');
console.log('Chart date, missing-data, totals and formatting checks passed.');
